JRuby support
ruby/io-wait pull request #2
Opened 2021-09-24 03:32 UTC by headius

This imports the JRuby code for io/wait, with tests green (see caveat) and hooked up to CI.

One test is skipped on JRuby due to jruby/jruby#6852, which will be fixed in JRuby 9.3.1.0.

This support is needed to release a JRuby-specific io-wait gem, a dependency of net-protocol. Without JRuby support in this gem we can't use any of the other net* gems.

2021-09-24 04:53 UTC, headius commented
I have no idea why the JRuby jobs are stuck.

2021-11-29 14:38 UTC, headius commented on lib/io/wait.rb
> +if RUBY_ENGINE == 'jruby'
I pushed more bits to properly package these libraries similar to digest.

FWIW I had not noticed that digest puts the `lib` dir under `ext/java/org/jruby/ext/digest`. It would seem cleaner to have it under `ext/java` but it is only a minor oddity.

2021-11-29 14:50 UTC, headius commented
I have pushed the missing bits for JRuby and rebased on current master.

Additional changes from previous review:

* Rakefile tweaks to get paths set properly for JRuby, with the JRuby-specific wait.rb moved under ext/java/lib.
* Gemspec tweaks to include lib/io/wait.jar and the Java ext files in the gem

This addresses both of @ahorek's review comments. I also tested that the built gem can install and replace the builtin io/wait in JRuby.

So it is pretty close now.

2021-11-30 07:30 UTC, headius commented on .github/workflows/jruby.yml
> +    runs-on: ${{ github.workflow }}-latest
Must be a copy/paste glitch. I'll fix and push.

2021-11-30 07:40 UTC, headius commented
Something is still not right with the JRuby builds.

2021-11-30 08:03 UTC, olleolleolle commented
is it missing a `bundle exec` before rake?

2021-11-30 08:39 UTC, headius commented
There are no dependenciesfor CRuby (dev or otherwise)  so no bundling is done in any of the builds.

I will add the necessary bits for JRuby.

2021-11-30 09:26 UTC, headius commented
Looks like we have a winner!

This can be squashed during merge, or if preferred I can rewrite the commits to better reflect the changes I made.

2021-12-07 14:59 UTC, headius commented
Pinging maintainers... I believe this is ready to merge and is necessary for JRuby 9.4 to source io-wait (and the net/* libraries that use it) from the gems. High priority for JRuby 9.4 release in the next month or two.

2021-12-12 06:03 UTC, nobu commented on Rakefile
> +    t.libs += ["ext/java/lib", "lib"]
Is `lib` used in JRuby?

2021-12-12 06:11 UTC, nobu commented on Rakefile
> +    t.libs += ["ext/java/lib", "lib"]
Hmmm, `lib/io/wait.jar` is...
Is `lib` directory considered a directory for generated binaries nowadays?
Then I'll add `/lib/` to `.gitignore`.

2022-01-10 12:44 UTC, headius commented on Rakefile
> +    t.libs += ["ext/java/lib", "lib"]
It can go anywhere that is on load path, but typically we have just used lib since JRuby ext gems ship precompiled.

2022-01-27 17:45 UTC, headius commented
I have updated this from master again. Is there anything else needed to merge?

2022-01-27 17:52 UTC, headius commented
The omitted test has been un-omitted, since that issue was fixed in JRuby 9.3.1.0 (current is 9.3.3.0).

2022-02-01 17:56 UTC, headius commented
I rebased this on master and it will merge now. I'm fine with merge commit or squashed.

2022-02-01 18:40 UTC, eregon commented on ext/java/org/jruby/ext/io/wait/IOWaitLibrary.java
> +        return RubyNumeric.int2fix(runtime, fptr.readyNow(context) ? 1 : 0);
Does it make sense to expose many JRuby internals like this, which might break as those APIs in JRuby might evolve?
A concrete example here is JRuby might be able to return a number of bytes for some IOs, but that would require updating this gem and handling both older & newer JRuby versions.

Wouldn't it be simpler and more encapsulated to simply have this gem noop on JRuby and just load the stdlib version?
That's probably the strategy we'll use for TruffleRuby, where we don't want to expose internals needlessly in public code, and extra APIs are only added where strictly needed (https://github.com/oracle/truffleruby/blob/master/doc/user/truffleruby-additions.md).

2022-02-01 21:10 UTC, headius commented on ext/java/org/jruby/ext/io/wait/IOWaitLibrary.java
> +        return RubyNumeric.int2fix(runtime, fptr.readyNow(context) ? 1 : 0);
I could ask the same thing about every extension gem for CRuby, which also expose CRuby to changes. Most of the calls here are unlikely to ever change. The IO byte count may be able to improve in the future, but it is not something we have had time or resources to try to do. This code in JRuby has had practically no changes in the past ten years. If there is a major change, the gem can support the last two major JRuby versions, which would allow transitioning over time. We take care not to drastically change anything that could be called from an external library.

Would it be easier if all the stdlib ext gems were no-ops on JRuby? Sure it would, but it would mean any security issues that come up or bugs to fix would require a full JRuby release. This library is quite small, and as it works fine it probably won't need many such changes, but we are not banking on that. JRuby will source as much of stdlib from gems as CRuby does, in order for us to match dependency graphs, align release cycles for bug and security fixes, and reduce the amount of code we maintain as part of JRuby itself.

If you would like to press this issue with other ruby-core folks I will participate and argue for reasonable changes to the stdlib gem list, including merging this and io-nonblock into IO proper or regarding other tiny gems that could be eliminated or merged. In the interim, I have a dozen gems I need to do this for before our 9.4 release, and very little time to push for such changes. We don't have the option of waiting for Ruby 3.2 with a slimmed down gem list, and people are already adding gems like net-* and io-wait to their Gemfiles, breaking their apps on JRuby.

2022-02-02 07:53 UTC, nobu requested changes
These lines seem unnecessary.

2022-02-02 07:58 UTC, nobu requested changes

2022-02-02 07:58 UTC, nobu commented on Rakefile
> +    end
`case`...`when` would be better for parallel conditions.
And setting `libs` here can make the next `Rake::TestTask.new(:test)` block unchanged.
```suggestion
when RUBY_ENGINE == 'jruby'
  require 'rake/javaextensiontask'
  Rake::JavaExtensionTask.new("wait") do |ext|
    require 'maven/ruby/maven'
    ext.source_version = '1.8'
    ext.target_version = '1.8'
    ext.ext_dir = 'ext/java'
    ext.lib_dir = 'lib/io'
  end
  libs = ["ext/java/lib", "lib"]
```

2022-02-02 12:23 UTC, eregon commented on ext/java/org/jruby/ext/io/wait/IOWaitLibrary.java
> +        return RubyNumeric.int2fix(runtime, fptr.readyNow(context) ? 1 : 0);
See https://bugs.ruby-lang.org/issues/18567, for TruffleRuby at least I wouldn't want to expose so many internals, and I think it's hard to sustain long term (e.g., who can maintain that Java code, harder to change anything in JRuby internals due to this, even though it's already a problem)
I think such code would be better in each Ruby implementation, and I think this shouldn't be a gem.
That said, it'd be enough if no gem depends on this gem, then it wouldn't matter it's declared as a default gem or not.

2022-02-02 15:06 UTC, headius commented on Rakefile
> +    end
I will make this change today

2022-02-02 15:07 UTC, headius commented on .gitignore
> +lib/io/wait.jar
The .gitignore already ignores *.so, so it should ignore our jar as well. I'm inclined to be very specific in .gitignore but if you would prefer *.jar I can do that.

2022-02-02 16:36 UTC, headius commented on ext/java/org/jruby/ext/io/wait/IOWaitLibrary.java
> +        return RubyNumeric.int2fix(runtime, fptr.readyNow(context) ? 1 : 0);
This is probably not the right place to debate whether the io-wait library should be a gem, so I'm going to consider this conversation resolved. It is a gem today, and we need to support it one way or another. This PR adds that support by providing an equivalent extension for JRuby.

2022-02-02 16:37 UTC, headius commented on Gemfile
> +
Newline at end of file is a pretty standard convention, isn't it?

2022-02-02 16:40 UTC, headius commented
I have addressed all review comments.

2022-02-03 00:20 UTC, hsbt approved these changes

2022-02-03 02:34 UTC, nobu commented on Rakefile
> +  when 'jruby'
I meant...
```ruby
case
when RUBY_VERSION < "2.6"
  ...
when RUBY_ENGINE == 'jruby'
  ...
```

2022-02-03 02:53 UTC, nobu commented on io-wait.gemspec
> +    spec.files += Dir["ext/java/**/*.{rb,java}", "lib/io/wait.jar"]
Why are both of `*.java` and `io/wait.jar` included?
And `ext/io/wait/*` too.

2022-02-03 04:51 UTC, headius commented on Rakefile
> +  when 'jruby'
I realize now this should actually be flipped in case someone tries to install this on JRuby 9.2, which is RUBY_VERSION == "2.5". The JRuby case should be used for all JRuby, and the rest should branch on 2.6. Will fix.

2022-02-03 04:55 UTC, headius commented on io-wait.gemspec
> +    spec.files += Dir["ext/java/**/*.{rb,java}", "lib/io/wait.jar"]
I believe I was just mimicking the C version, which includes sources for building. The Java sources might be useful for debugging, but since we don't support that I will remove them.

2022-02-03 06:39 UTC, nobu approved these changes

2022-02-03 06:40 UTC, merged

2022-02-03 08:45 UTC, hsbt commented
🎉

2022-02-03 12:02 UTC, nobu commented on Rakefile
> +  when 'jruby'
https://github.com/nobu/io-wait/commit/e0ccd86d6e4bdef562a2d1ff2b4a57f8b9c3c589
Seems not passing on JRuby 9.2.
It may be installable and working a little, but would’t be usable for development and building the gem.

2022-02-03 13:37 UTC, headius commented
Thank you both!